In [9]:
# Import necessary libraries
import pandas as pd
import random
import numpy as np

In [10]:
# Load the two CSV files into pandas DataFrames
rides_df = pd.read_csv('Taxi_Trips_(2024-)_20251125.csv')  # Replace with your actual path
cars_df = pd.read_csv('unique_make_model_year.csv')    # Replace with your actual path

C:\Users\fredb\AppData\Local\Temp\ipykernel_20372\1651477534.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  rides_df = pd.read_csv('Taxi_Trips_(2024-)_20251125.csv')  # Replace with your actual path

In [11]:
print(len(rides_df))
print(len(cars_df))

615718
1048

In [12]:
# Ensure the cars_df is shuffled so the car selection is random
cars_df_shuffled = cars_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Calculate CO2 emissions per km for each car (using the MPG column)
cars_df_shuffled['CO2 per km (kg)'] = (3.89 / cars_df_shuffled['MPG']) * 1609.34

# Generate random indices to assign to the rides dataset
random_car_indices = np.random.choice(cars_df_shuffled.index, size=len(rides_df), replace=True)

# Add car details to the rides dataset using the random indices
rides_df['Vehicle Make'] = cars_df_shuffled.loc[random_car_indices, 'Vehicle Make'].values
rides_df['Vehicle Model'] = cars_df_shuffled.loc[random_car_indices, 'Vehicle Model'].values
rides_df['Vehicle Model Year'] = cars_df_shuffled.loc[random_car_indices, 'Vehicle Model Year'].values
rides_df['MPG'] = cars_df_shuffled.loc[random_car_indices, 'MPG'].values
rides_df['CO2 emission (g/km)'] = cars_df_shuffled.loc[random_car_indices, 'CO2 per km (kg)'].values
# Save the resulting merged dataset to a new CSV file
rides_df.to_csv('texas_Oct_2024_merged.csv', index=False)

print("Merging completed and saved!")

Merging completed and saved!

# TEST

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('texas_Oct_2024_merged.csv')
# data = pd.read_csv('merged_datasetAB_finaldatetime.csv')

C:\Users\fredb\AppData\Local\Temp\ipykernel_37852\3315375867.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('texas_Oct_2024_merged.csv')

In [5]:
# columns 17, 18, 20, 21 (0-based index)
cols = [17, 18, 20, 21]

# drop rows with NaN in any of these columns
data = data.dropna(subset=data.columns[cols])

# save the cleaned data
data.to_csv('texas_Oct_2024_merged.csv', index=False)

In [3]:
data.head()

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,...,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location,Vehicle Make,Vehicle Model,Vehicle Model Year,MPG,CO2 emission (g/km)
0,ffd767700ca6ed91ffc984145c3d3ab44f443c1e,a700f56e643e08db0d6a189c37c6faa7fbf553b925b9b6...,10/31/2025 09:00:00 PM,10/31/2025 09:15:00 PM,900,9.0,NaN,NaN,51.0,37.0,...,-87.570058,POINT (-87.5700582686 41.6906333472),41.809084,-87.632425,POINT (-87.6324245245 41.8090844303),FORD,VAN,2002,12.0,521.694383
1,ffc55e13f772e8a1ec0b23e89d0e62160dd4ad0a,1652b7aa113cbd2d709fedd1eedcfcf20c4c809a079a5c...,10/31/2025 09:00:00 PM,10/31/2025 09:15:00 PM,788,3.51,NaN,NaN,24.0,7.0,...,-87.676356,POINT (-87.6763559892 41.9012069941),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),Dodge,CARAVAN,2007,19.0,329.491189
2,fde384e79caae083780512e5a657009d15353267,396892a80daeabb209e6a8a53a4beb62d71771dcf69611...,10/31/2025 09:00:00 PM,10/31/2025 09:15:00 PM,"1,017",3.04,1.703183e+10,1.703108e+10,28.0,8.0,...,-87.657233,POINT (-87.6572331997 41.8852813201),41.899156,-87.626211,POINT (-87.6262105324 41.8991556134),IC,M LINE SHUTTLE BUS,2013,12.0,521.694383
3,fd150bf64995505db8ab246e88c10e22192be093,cd87d0b59d5a8c56ddd35fea328811734a4a7c965d249d...,10/31/2025 09:00:00 PM,10/31/2025 09:00:00 PM,269,1.07,1.703108e+10,1.703108e+10,8.0,8.0,...,-87.626211,POINT (-87.6262105324 41.8991556134),41.907520,-87.626659,POINT (-87.6266589003 41.9075200747),TOYOTA,PRIUS,2012,50.0,125.206652
4,fb1a0fa3919045d6c001fcbe11f33e5e62acb98c,0cf1289b8acf557ac9673f1b9a4b544f295d83edb49af8...,10/31/2025 09:00:00 PM,10/31/2025 09:15:00 PM,623,2.29,1.703108e+10,1.703128e+10,8.0,28.0,...,-87.612945,POINT (-87.6129454143 41.8919715078),41.879255,-87.642649,POINT (-87.642648998 41.8792550844),TOYOTA,PRIUS,2019,58.0,107.936769

In [37]:
# Convert 'Trip Start Timestamp' to datetime
data['time'] = pd.to_datetime(data['Trip Start Timestamp'])
# Generate random seconds between 0 and 15 minutes (0 to 900 seconds)
random_seconds = np.random.randint(0, 15*60 + 1, size=len(data))

# Add the random timedelta to the 'time' column
data['time'] = data['time'] + pd.to_timedelta(random_seconds, unit='s')
# Sort by timestamp
data.sort_values(by='time', inplace=True)

# Save back to CSV if needed
# df_sorted.to_csv("sorted_file.csv", index=False)

C:\Users\fredb\AppData\Local\Temp\ipykernel_20372\72648017.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['time'] = pd.to_datetime(data['Trip Start Timestamp'])

In [19]:
data.sort_values(by='created_date', inplace=True)

In [20]:
data.iloc[0]['created_date']

'2016-11-30 17:43:51-06:00'

In [38]:
data.head()

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,...,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location,Vehicle Make,Vehicle Model,Vehicle Model Year,MPG,CO2 emission (g/km),time
615561,1a2853154d385ed7197dd671cf16134935330dc6,e637e1afe0dab0e2d04c635335602caf1045d43e3741c2...,10/01/2025 09:15:00 PM,10/01/2025 09:15:00 PM,300,1.0,NaN,NaN,1.0,2.0,...,POINT (-87.6701668569 42.0096228806),42.001571,-87.695013,POINT (-87.6950125892 42.001571027),FORD,TAURUS,2015,23.0,272.188374,2025-10-01 21:15:03
615537,f7d8158af0c171296fbbd59ae3a724b54be2c687,c3fe9312c9722befcf39d581225faa3d8dfae24c783c74...,10/01/2025 09:15:00 PM,10/01/2025 09:30:00 PM,650,2.89,1.703108e+10,1.703133e+10,8.0,33.0,...,POINT (-87.6262149064 41.8925077809),41.859350,-87.617358,POINT (-87.6173580061 41.859349715),TOYOTA,VENZA,2013,27.0,231.864170,2025-10-01 21:15:09
615651,96069aefaa9bd2028dd74d7b6d4efcaf5fbfa544,2a29bcc02d98eb9e748a8427ffd773934047f77e20f703...,10/01/2025 09:15:00 PM,10/01/2025 09:45:00 PM,"1,832",20.99,1.703198e+10,NaN,76.0,NaN,...,POINT (-87.9030396611 41.9790708201),NaN,NaN,NaN,TOYOTA,COROLLA,2015,30.0,208.677753,2025-10-01 21:15:10
615706,e154550c865443f2c0b7705c61c15c4e92f7d295,8b16fbd9daba8152a0e6afae54e6b3f343aae2a69b56b1...,10/01/2025 09:15:00 PM,10/01/2025 09:15:00 PM,317,1.19,NaN,NaN,8.0,32.0,...,POINT (-87.6333080367 41.899602111),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),FORD,EXPEDITION,2021,19.0,329.491189,2025-10-01 21:15:17
615578,33384a37e0e54d89cf9d2cee28c14b79cbb29894,5adbc97abe353b4ad223abfb31d0311bd30800e15f43a2...,10/01/2025 09:15:00 PM,10/01/2025 09:30:00 PM,"1,477",16.0,NaN,NaN,76.0,24.0,...,POINT (-87.913624596 41.9802643146),41.901207,-87.676356,POINT (-87.6763559892 41.9012069941),FORD,ECONOLINE,2012,14.0,447.166614,2025-10-01 21:15:17

In [6]:
data.columns

Index(['Trip ID', 'Taxi ID', 'Trip Start Timestamp', 'Trip End Timestamp',
       'Trip Seconds', 'Trip Miles', 'Pickup Census Tract',
       'Dropoff Census Tract', 'Pickup Community Area',
       'Dropoff Community Area', 'Fare', 'Tips', 'Tolls', 'Extras',
       'Trip Total', 'Payment Type', 'Company', 'Pickup Centroid Latitude',
       'Pickup Centroid Longitude', 'Pickup Centroid Location',
       'Dropoff Centroid Latitude', 'Dropoff Centroid Longitude',
       'Dropoff Centroid  Location', 'Vehicle Make', 'Vehicle Model',
       'Vehicle Model Year', 'MPG', 'CO2 emission (g/km)'],
      dtype='object')

In [35]:
data.iloc[0][28]

Timestamp('2025-10-01 21:15:00')

In [40]:
(data.iloc[2+1][28] - data.iloc[2][28]).seconds

7

In [43]:
from tqdm import tqdm

In [44]:
ints = []
for i in tqdm(range(len(data)-1)):
    ints.append((data.iloc[i+1][28] - data.iloc[i][28]).seconds)

100%|████████████████████████████████████████████████████████████████████████| 615717/615717 [02:04<00:00, 4962.15it/s]

In [45]:
np.average(ints)

4.209721349256233

In [46]:
np.max(ints)

634

In [47]:
np.min(ints)

0

In [48]:
np.var(ints)

90.32696172412308

In [4]:
# Select columns by index
cols_to_check = data.columns[[17, 18, 20, 21]]

# Check for any NaN in those columns
nan_rows = data[data[cols_to_check].isna().any(axis=1)]

print(nan_rows)
print(f"Number of rows with NaN: {len(nan_rows)}")

                                         Trip ID  \
19      e462d735b7b5dd9f1fe8098c9acc4e153f00dd88
23      e11be8c37416d87ab911ee46f0e3a5aeaf416f73
31      d8aa23846948720c270aea6d42d2fa54200ce082
32      d73a0f130bba20f94abd0978b3e2f853623d1943
56      b543c42bc43eda147909816d752bbfa64e70fd21
...                                          ...
615672  b0eb38d7c6c69684d8a92300157db9f01d7a91f7
615692  c9ca6ea3e54fa1186c7f024691a72be94946d7b4
615709  e3622e81015a0bde766b569f9e1648750331dec7
615714  e8bab118e99316f2096128b5756db1379995c725
615715  ea06855d3e7769c094fb75080f5074bc24f20f01

                                                  Taxi ID  \
19      a79085175f766b61aa2ed8e09960e466cc7c20c8539a0e...
23      ee0403d56ad861c2f3d4b1244497b07a47b61d3f9078de...
31      3b443d58fee461cd803cdf9a032f474964aabb042fc5f6...
32      d511072131b602026bdb9faa5491d15c3af8d62dc00659...
56      19447854f6105afc7307d18998685917b36bbbb2c8a7e5...
...                                                   ...
615672  79871a444f99170269396b5e6b08b90ef1def10a76732e...
615692  3d77b9fc21a6484a88ca7f79552d5ea5e712563dfa3051...
615709  1df52fc60f8edec541c9a014b8ecf83c86f471b328635c...
615714  d86cc058dfd5bc89d698b8767fe48fd9a0fe8ed8c3111c...
615715  73052f4ccaf4e0fa9178722e491f8e5eda869f56e08aa4...

          Trip Start Timestamp      Trip End Timestamp Trip Seconds  \
19      10/31/2025 09:00:00 PM  10/31/2025 09:15:00 PM          980
23      10/31/2025 09:00:00 PM  10/31/2025 09:00:00 PM          739
31      10/31/2025 09:00:00 PM  10/31/2025 09:15:00 PM          942
32      10/31/2025 09:00:00 PM  10/31/2025 09:00:00 PM          320
56      10/31/2025 09:00:00 PM  10/31/2025 09:30:00 PM        1,680
...                        ...                     ...          ...
615672  10/01/2025 09:15:00 PM  10/01/2025 09:45:00 PM        1,424
615692  10/01/2025 09:15:00 PM  10/01/2025 09:15:00 PM            0
615709  10/01/2025 09:15:00 PM  10/01/2025 09:45:00 PM        1,212
615714  10/01/2025 09:15:00 PM  10/01/2025 09:45:00 PM        2,010
615715  10/01/2025 09:15:00 PM  10/01/2025 09:15:00 PM           60

       Trip Miles  Pickup Census Tract  Dropoff Census Tract  \
19            6.3                  NaN                   NaN
23           4.28                  NaN                   NaN
31          10.16         1.703198e+10                   NaN
32            0.0                  NaN          1.703124e+10
56            4.2                  NaN                   NaN
...           ...                  ...                   ...
615672       9.53                  NaN                   NaN
615692        0.0         1.703108e+10                   NaN
615709      21.85                  NaN                   NaN
615714      16.36                  NaN                   NaN
615715        0.0                  NaN                   NaN

        Pickup Community Area  Dropoff Community Area  ...  \
19                       76.0                     NaN  ...
23                        NaN                     NaN  ...
31                       76.0                     NaN  ...
32                        NaN                    24.0  ...
56                       28.0                     NaN  ...
...                       ...                     ...  ...
615672                   76.0                     NaN  ...
615692                    8.0                     NaN  ...
615709                   56.0                     NaN  ...
615714                   76.0                     NaN  ...
615715                    NaN                     NaN  ...

       Pickup Centroid Longitude              Pickup Centroid Location  \
19                    -87.913625   POINT (-87.913624596 41.9802643146)
23                           NaN                                   NaN
31                    -87.903040  POINT (-87.9030396611 41.9790708201)
32                           NaN                                   NaN
56                    -87.663518   POINT (-87.6635175498 41.874005383)
...                          ...                                   ...
615672                -87.913625   POINT (-87.913624596 41.9802643146)
615692                -87.631864  POINT (-87.6318639497 41.8920421365)
615709                -87.769615  POINT (-87.7696154528 41.7925923603)
615714                -87.913625   POINT (-87.913624596 41.9802643146)
615715                       NaN                                   NaN

       Dropoff Centroid Latitude Dropoff Centroid Longitude  \
19                           NaN                        NaN
23                           NaN                        NaN
31                           NaN                        NaN
32                     41.906651                 -87.665338
56                           NaN                        NaN
...                          ...                        ...
615672                       NaN                        NaN
615692                       NaN                        NaN
615709                       NaN                        NaN
615714                       NaN                        NaN
615715                       NaN                        NaN

                  Dropoff Centroid  Location Vehicle Make       Vehicle Model  \
19                                       NaN         FORD  EXPEDITION XLT MAX
23                                       NaN          KIA         SPORTAGE LX
31                                       NaN     INFINITI                QX80
32      POINT (-87.6653376596 41.9066507664)     CADILLAC            ESCALADE
56                                       NaN       JAGUAR              F PACE
...                                      ...          ...                 ...
615672                                   NaN     MERCEDES                BENZ
615692                                   NaN    CHEVROLET            SUBURBAN
615709                                   NaN      LINCOLN             AVIATOR
615714                                   NaN    CHEVROLET                 VAN
615715                                   NaN        VOLVO                 S90

        Vehicle Model Year   MPG CO2 emission (g/km)
19                    2025  16.0          391.270787
23                    2021  22.0          284.560573
31                    2021  11.0          569.121145
32                    2021  20.0          313.016630
56                    2021  22.0          284.560573
...                    ...   ...                 ...
615672                2022  19.0          329.491189
615692                2024  25.0          250.413304
615709                2023  18.0          347.796256
615714                2010  13.0          481.564046
615715                2019  28.0          223.583307

[53960 rows x 28 columns]
Number of rows with NaN: 53960

In [9]:
print("Minimum:", data['Pickup Centroid Latitude'].min())
print("Minimum:", data['Pickup Centroid Latitude'].max())
print("Maximum:", data['Pickup Centroid Longitude'].min())
print("Maximum:", data['Pickup Centroid Longitude'].max())

Minimum: 41.660136051
Minimum: 42.015934376
Maximum: -87.913624596
Maximum: -87.534902901

In [10]:
print("Minimum:", data['Dropoff Centroid Latitude'].min())
print("Minimum:", data['Dropoff Centroid Latitude'].max())
print("Maximum:", data['Dropoff Centroid Longitude'].min())
print("Maximum:", data['Dropoff Centroid Longitude'].max())

Minimum: 41.660136051
Minimum: 42.021223593
Maximum: -87.913624596
Maximum: -87.534902901